### PR TITLE
Inspector config hooks

### PR DESCRIPTION
**Pull request by laverdet**
I wrote a mod that enables the v8 inspector in isolates but I needed some config hooks to get it done.

There's another change to `create` as well.. There was a race condition here if that function was called more than once before the first one was done completing. This would end up creating multiple isolates for the same user before the first one was initialized. So instead if you call the function more than once it will just return a promise to the previous not yet initialized isolate.

The mod is here: https://github.com/laverdet/screepsmod-inspector

### CODE REVIEW

**Comment by artch** [comment]
Have you seen this race condition ever happening? It should never be the case, since the same user is not supposed to be executed in two threads simultaneously.

**Comment by laverdet** [comment]
It happened for the source keepers, flooded the logs until I put the promise workaround in place.

**Comment by Ramblurr** [comment]
Looks like this patch needs to be rebased

**Comment by artch** [comment]
Merged to `ptr` branch. It will be merged to master in a few days, so this PR can still remain open.

**Pull request merged**
